name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: "1.16"
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: make test
        env:
          GOARGS: "-v -race"
          GOMAXPROCS: 8
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tmp/cover.out
      - run: make demo
