version: 2.1

commands:
  check:
    steps:
      - checkout
      - run:
          name: 'Run checks'
          command: make test

jobs:    
  test_go_1_11:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.11
    steps:
      - check
    
  test_go_1_12:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.12
    steps:
      - check
    

workflows:
  version: 2
  test:
    jobs:
      - test_go_1_11
      - test_go_1_12
